### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ThatMrWayne**
許哲瑋

http://54.172.41.91:3000/

Please review, thank you!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Get error response when I search 館
2. If you decide not to use React, remove react libraries from your page.

**Comment by ThatMrWayne** [comment]
1. fix error for this issue.
2. got it ! react libraries have been removed.

Please help review again. Thank you!

http://54.172.41.91:3000/

**Comment by cwpeng** [comment]
I can approve only if you re-request me review.

**Comment by ThatMrWayne** [comment]
Sorry for not requesting for review.

This is the website url:
http://54.172.41.91:3000/

Please help review.
Thank you!~

**Comment by cwpeng** [comment]
No, not leave message. Re-request review from right side in this page.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by ThatMrWayne** [comment]
Now I understand.  Thank you !

**Pull request merged**
