### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ThatMrWayne**
許哲瑋

http://54.172.41.91:3000/
http://54.172.41.91:3000/attraction/14
http://54.172.41.91:3000/attraction/39

Please review, thank you!

### CODE REVIEW

**Comment by cwpeng** [comment]
Line height of attraction information below, should be larger. Fix it and leave comment for me to review again.

**Comment by ThatMrWayne** [comment]
Information bottom line height has been revised.
Please check again. Thank you.

http://54.172.41.91:3000/
http://54.172.41.91:3000/attraction/14
http://54.172.41.91:3000/attraction/39

**Comment by cwpeng** [comment]
I mean line-height of text, not padding-bottom of entire div block.

**Comment by ThatMrWayne** [comment]
Sorry for misunderstanding.  
Please check again. Thank you!

http://54.172.41.91:3000/
http://54.172.41.91:3000/attraction/14
http://54.172.41.91:3000/attraction/39

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
