### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ThatMrWayne**
許哲瑋

http://54.90.113.160:3000/api/attractions?page=1
http://54.90.113.160:3000/api/attractions?page=4
http://54.90.113.160:3000/api/attractions?page=0&keyword=溫泉
http://54.90.113.160:3000/api/attraction/45
http://54.90.113.160:3000/api/attraction/100
http://54.90.113.160:3000/api/attraction/abc

### CODE REVIEW

**Comment by cwpeng** [comment]
"nextPage" in http://54.90.113.160:3000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89 should be null, because page 0 is the final page in this searching result.

Fix it, create new commit and leave comment here for me to review again.

**Comment by ThatMrWayne** [comment]
fix for nextPage issue:
http://54.90.113.160:3000/api/attractions?page=0&keyword=溫泉

Please review, thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK.

But, we will not use 2 connections and cursors here, just use 1.
```
        cursor1= cnx1.cursor(dictionary=True)
        cursor2 = cnx2.cursor(dictionary=True)
```
If there is keyword input, you use connection 1, connection 2 is redundant, vice versa.

**Comment by ThatMrWayne** [comment]
Got it! Thanks for review.
redundant connection has been removed.
Please review. Thank you.

**Review by cwpeng — APPROVED** [review]
Done. Good Job. ~

**Pull request merged**
